services:
  app:
    build: .
    container_name: brutus-dapp-web
    restart: always
    env_file:
      - .env
    networks:
      - web
    ports:
      - 8001:3000

networks:
  web:
    external: true