name: Sync docs to web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://stevenstc:${{ secrets.FINE_GRAINED_PAT }}@github.com/brutustoken/BRUTUS-TOKEN.git

      - name: Create or update web branch
        run: |

          git checkout main
          # Check out the web branch or create it if it doesn't exist
          git fetch origin web || echo "web branch does not exist"
          git checkout web || git checkout --orphan web

          # Clear the branch and copy the docs folder content to root
          git rm -rf . || true

          git checkout main -- docs
          mv docs/* ./
          rm -rf docs

          git add .
          git commit -m "Sync docs folder to web branch"
        
          # Empujar los cambios a la rama web
          git push origin web --force

          